### ISSUE TITLE
Ghost lights when uninstalling mod

### ISSUE THREAD

**Issue by ViciousBadger** [pnk2u/More-Torch-Variants#2]
Hi, I get strange ghost lights where torches were placed before when the mod is uninstalled. The only way to get rid of them is to correctly guess where the torches were and place a block there and then remove it. Know of a better way?

**Comment by pnk2u** [comment]
Unfortunately it is so, that the same would happen if you "removed" the base game torches as if they're a mod, it's just Minecraft's code as far as I'm aware. I unfortunately do not at the time know of any easy way to remedy this in an easier fashion than you're already doing. If I do find one - please let me know what version you're playing on so I know what to look for - I will come back to you and let you know.

**Comment by ViciousBadger** [comment]
Thanks for responding. I managed to find a solution, turns out using WorldEdit's "//update" command will recalculate lighting for the selected chunks! All is good now ☀️

**Comment by pnk2u** [comment]
Ah, that's lovely to hear. I'm glad you found a solution. Thank you for sharing that solution with me, so I can share it with anyone else running into an issue like that. Maybe I'll add it to the mod's description pages if it comes up again. (:
