### ISSUE TITLE
[Mod Integration] Not Enough Animations

### ISSUE THREAD

**Issue by heide-oficial** [pnk2u/More-Torch-Variants#3]
I don't know if this is something that needs to be added to More Torch Variants (MStV+) or to [Not Enough Animations](https://modrinth.com/mod/not-enough-animations/versions), but vanilla torches actually are helded differently with Not Enough Animations, which make it look better with the [First Person Mode](https://modrinth.com/mod/first-person-model/versions)l mod.

So, as you can see in the screeshots bellow, torches from More Torch Variants (MStV+) aren't affected by the Not Enough Animations effect, and it would be awesome if the modded torches had that feature as well!

Vanilla torch with Not Enough Animations:
![vanilla_torch](https://github.com/user-attachments/assets/20db7ebc-8c6e-4c8c-ae0b-b34b30ce87b5)

Modded torch from MStV+ with Not Enough Animations:
![mstv+_torch](https://github.com/user-attachments/assets/09f97b77-df7f-4b9d-86ec-3c74e9a9c2b6)

**Comment by pnk2u** [comment]
Good idea, I'll do that later and let you know when that update is out.

**Comment by pnk2u** [comment]
The version 1.0.6, that I've just uploaded, should provide the described functionality. Please let me know if it now works as expected.

**Comment by heide-oficial** [comment]
Worked like a charm! Thank you for the support and for your awesome mods!! Love having this variety in Minecraft!
![2024-11-08_18 11 20](https://github.com/user-attachments/assets/38d825cc-f804-454c-8f53-67e59438a2ea)
